wolt_assignment_dbt:
  target: "{{ env_var('DBT_TARGET', 'dev') }}"
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: "{{ env_var('DBT_BQ_DEV_PROJECT') }}"
      dataset: "{{ env_var('DBT_BQ_DEV_DATASET', 'analytics_dev') }}"
      location: "{{ env_var('DBT_BQ_LOCATION', 'EU') }}"
      keyfile: "{{ env_var('DBT_BQ_DEV_KEYFILE') }}"
      threads: "{{ env_var('DBT_THREADS_DEV', 4) | int }}"
      job_execution_timeout_seconds: 300
      job_retries: 1
      priority: interactive

    prod:
      type: bigquery
      method: service-account
      project: "{{ env_var('DBT_BQ_PROD_PROJECT') }}"
      dataset: "{{ env_var('DBT_BQ_PROD_DATASET', 'analytics_prod') }}"
      location: "{{ env_var('DBT_BQ_LOCATION', 'EU') }}"
      keyfile: "{{ env_var('DBT_BQ_PROD_KEYFILE') }}"
      threads: "{{ env_var('DBT_THREADS_PROD', 8) | int }}"
      job_execution_timeout_seconds: 600
      job_retries: 2
      priority: interactive
