wolt_assignment_dbt:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: "wolt-assignment-489610"
      dataset: "analytics_dev"
      location: "EU"
      keyfile: "/Users/fhaghighi/Job apply/Wolt/Wolt_Assignment/credentials/wolt-assignment-489610-903badd90388.json"
      threads: 4
      job_execution_timeout_seconds: 300
      job_retries: 1
      priority: interactive

    prod:
      type: bigquery
      method: service-account
      project: "wolt-assignment-489610"
      dataset: "analytics_prod"
      location: "EU"
      keyfile: "/Users/fhaghighi/Job apply/Wolt/Wolt_Assignment/credentials/wolt-assignment-489610-aa4357687d44.json"
      threads: 8
      job_execution_timeout_seconds: 600
      job_retries: 2
      priority: interactive
