select
    order_item_sk,
    order_sk,
    customer_sk,
    item_key_sk,
    item_scd_sk,
    promo_key,
    time_order_received_utc as order_ts_utc,
    order_date_utc,
    order_date_berlin as order_date,
    item_count,
    unit_base_price_gross_eur,
    discount_pct_applied,
    unit_discount_amount_gross_eur,
    unit_final_price_gross_eur,
    line_base_amount_gross_eur,
    line_discount_amount_gross_eur,
    line_final_amount_gross_eur,
    is_promo_item,
    item_name_en,
    item_name_de,
    item_name_preferred,
    item_category,
    brand_name,
    vat_rate_pct
from {{ ref('int_wolt_order_items_promoted') }}
