select
    order_sk,
    customer_sk,
    time_order_received_utc as order_ts_utc,
    order_date_utc,
    order_date_berlin as order_date,
    extract(hour from time_order_received_utc) as order_hour_utc,
    format_date('%A', order_date_berlin) as order_day_name,
    delivery_distance_line_meters,
    total_basket_value_eur,
    wolt_service_fee_eur,
    courier_base_fee_eur,
    basket_plus_service_fee_eur,
    total_customer_paid_eur,
    total_item_count,
    distinct_item_count,
    promo_line_count,
    promo_item_count,
    contains_promo_flag,
    model_line_base_amount_gross_eur,
    model_line_discount_amount_gross_eur,
    model_line_final_amount_gross_eur,
    customer_order_number,
    is_first_order_for_customer
from {{ ref('int_wolt_orders_enriched') }}
